name: Build and Push into private ACR Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout repository
        uses: actions/checkout@v4

      # 1. Authenticate to Azure using your Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2. Set the subscription explicitly
      - name: Set Azure Subscription
        run: |
          az account set --subscription "mmani-ovcp2-sub-torque"

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: mmaniacr
          containerAppName: helloworldapp
          resourceGroup: mmani-azure-resource-group

#      - name: Trigger ACR Task
#        run: |
#          az acr task run \
#            --registry mmaniacr \
#            --resource-group mmani-azure-resource-group \
#            --name build-task 

