name: Build and Push into private ACR Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Trigger ACR Task
        run: |
          az acr task run \
            --registry mmaniecr \
            --name build-task
